---

- name: AWS Web Setup
  hosts: tag_Name_hostileadminweb
  user: ec2-user
  become: yes
  become_user: root

  vars_files:
    - vars/main.yml

  tasks:
    - name: Install AWS EPEL, nginx
      command: amazon-linux-extras install "{{ item }}" -y
      with_items:
        - epel
        - nginx1
      when: update == "true"
    - name: Install/update packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - nc
        - nmap
        - '*'
      when: update == "true"

    - name: Prepare to checkout git repo
      file:
        state: absent
        path: "{{ docroot  }}"
      when: deployweb == "true"
    - name: Git checkout
      git:
        repo: 'https://github.com/vrwmiller/petabit.io'
        dest: "{{ docroot }}"
        accept_hostkey: yes
        single_branch: yes
        version: master
      when: deployweb == "true"

    - name: Start nginx
      service:
        name: nginx
        enabled: yes
        state: restarted

    - name: Reboot
      reboot:
      when: reboot == "true"
