---

- hosts: tag_Name_hostileadminweb
  user: ec2-user
  become: yes
  become_user: root
  tasks:
  - name: Enable EPEL
    command: amazon-linux-extras install epel -y
  - name: Install nginx
    command: amazon-linux-extras install nginx1 -y
  - name: Install git
    yum:
      name: git
      state: latest
  - name: Install netcat
    yum:
      name:
        - nc
      state: latest
  - name: Update the rest
    yum:
      name:
        - '*'
      state: latest
  - name: Prepare to checkout git repo
    file:
      state: absent
      path: /usr/share/nginx/html/
  - name: Git checkout
    git:
      repo: 'https://github.com/vrwmiller/petabit.io'
      dest: /usr/share/nginx/html
      accept_hostkey: yes
      version: master
  - name: Start nginx
    service:
      name: nginx
      state: started
